name: ZAP Baseline

on:
  push:
    branches: [ main ]          # run after merge
  pull_request:                 # run on every PR
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'         # nightly 02:00 UTC
  workflow_dispatch:            # manual “Run workflow” button


jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Django
        run: |
          pip install -r requirements.txt
          python manage.py migrate
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:8000'
          fail_action: true
          cmd_options: '-w 3'
