name: ZAP Baseline

on:
  schedule:
    - cron: '0 2 * * *'   # nightly at 02:00 UTC
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Django
        run: |
          pip install -r requirements.txt
          python manage.py migrate
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:8000'
          fail_action: false
          cmd_options: '-w 1000'
